# Generated by Django 3.2.8 on 2021-10-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img_url',
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
